### ISSUE TITLE
Implement addUserToGroup and removeUserFromGroup in frontend

### ISSUE THREAD

**Issue by SpeckiJ** [fs-geofs/UserManager#1]
The two methods are already [in the code](https://github.com/christophfriedrich/UserManager/blob/216d4ac13d1ef66d20b8afa1190e64484f683108/public/index.html#L245), but don't do anything yet.

**Comment by christophfriedrich** [comment]
Why didn't you just *transfer* the actual old issue? AFAIK that's possible.

**Comment by SpeckiJ** [comment]
@christophfriedrich Unfortunately the "Transfer Issue" Button only lets me transfer the issue within a single organization/person (e.g. inside speckij or inside fs-geofs). 

As there is no discussion attached to this Issue just transferring it manually should be sufficient.

**Comment by christophfriedrich** [comment]
Ah okay. Yeah it's not a big deal, I just principally dislike it when things are duplicated, hence my comment.

**Comment by SpeckiJ** [comment]
Should be merged with https://github.com/fs-geofs/UserManager/pull/9 and is now live
