### ISSUE TITLE
include web assets in build binary

### ISSUE THREAD

**Issue by noerw** [fs-geofs/UserManager#11]
There's a simple tool for that ([packr2](https://github.com/gobuffalo/packr/tree/master/v2)), which simply replaces the `go build` command.

This is a tradeoff:
- `+` simpler & more consistent deployment
- `-` adds a new (easy to install) dependency on the build machine
- `o` ~makes trying out development frontend versions slightly more complicated~
  - this should be a non-issue, as the frontend can be hosted anywhere given a custom `API_BASE` value

**Comment by christophfriedrich** [comment]
Is this just for the Go part (i.e. backend)?

What do you think about the CDN calls in the frontend?

**Comment by noerw** [comment]
This is about the deployment of the app (so there is just a single file), frontend development should keep working as is.

We could also vendor the JS dependencies and embed them in the built binary in the same way. I'd prefer that to using a CDN but was too lazy as of now.
