### ISSUE TITLE
Creating a group creates empty members entry

### ISSUE THREAD

**Issue by christophfriedrich** [fs-geofs/UserManager#12]
In group's member lists, the items are separated by semicolons. 

But for some reason, the member list string of the "video" group _starts_ with such a semicolon:
`members: ";cn=Christoph..."`

Resulting in this rendering in the frontend:
> **videos:** , Christoph, ...

I assume this is a problem in the backend?

**Comment by noerw** [comment]
It's a user without displayname, (i.e. admin i guess)

**Comment by SpeckiJ** [comment]
I checked the LDAP and there was an empty member entry in the group. No idea where that came from.

**Comment by christophfriedrich** [comment]
News: It's reproducible!

The "videos" group was the only one that was created through the UserManager interface (all others were created during the initial setup of the LDAP).

I just did:
- create group "test" via GUI at the bottom of the page
- assign some user (tested it with myself) to that group via the dropdown in the big table

outcome:
> **test:** , Christoph

**Comment by SpeckiJ** [comment]
https://github.com/fs-geofs/UserManager/blob/b7a3b9a5b878e6f37dc64ab1c848da67bb81574c/LDAPHandler.go#L178

This should probably not be there. will fix

**Comment by SpeckiJ** [comment]
This should be resolved with https://github.com/fs-geofs/UserManager/commit/f0fac877c59dc2e692c5318236962c048cdddec6

LDAPAdmin is now added per default to all groups to comply with https://tools.ietf.org/html/rfc2256#section-7.10 disallowing empty groups. To compensate for that LDAPAdmin is not returned by the API in either Users or Groups Requests.
