### ISSUE TITLE
Remove unneccessary parameters from API requests, unify parameter names

### ISSUE THREAD

**Issue by christophfriedrich** [fs-geofs/UserManager#7]
Following up on the discussion in #5:

> This stems from the fact that the backend differs between "GroupUser" which is a combination of username and group association and "User", which has a password and fachschaft.

> At the moment of programming this seemed to be the best option, as we can do proper validation now when initializing the structs. If all properties would be in a single struct, they would often be nil and validation becomes more difficult (what properties are needed for this specific request? does password need to be set now? Or is it a groupAdd request that does not have a password? )

It may have been handy at the moment of programming, but in the long run I still don't see the point of requesting more information than neccessary just to save a few `if`s on the serverside.

I would like the requested parameters to be like this:

- [x] `users/add`: username, password, fs [like now]
- [x] `users/remove`: username [difference: no password, no fs]
- [x] `users/addToGroup`: username; groupname [group*name* instead of group for consistency]
- [x] `users/removeFromGroup`: username; groupname [group*name* instead of group for consistency]
- [x] `users/changePassword`: username, password [no fs]
- [x] `groups/add`: groupname [like now]
- [x] `groups/remove`: groupname [like now]

That would make the public-facing API a lot nicer and much more consistent and logical.

**Comment by SpeckiJ** [comment]
Should all be fixed/implemented with https://github.com/fs-geofs/UserManager/pull/9
