### ISSUE TITLE
Remove user from group doesn't work in backend?

### ISSUE THREAD

**Issue by christophfriedrich** [fs-geofs/UserManager#8]
I just implemented #1 and tested it: Adding a group works fine, but removing failed with error message:

> Error Removing User from Group: LDAP Result Code 34 "Invalid DN Syntax": invalid DN"

I really hope I'm not falsly blaming it on someone else again, but this time I *really* think I did everything correct in the frontend (see 7709816 for the frontend code)

![grafik](https://user-images.githubusercontent.com/17781682/56863325-3b83c800-69b5-11e9-8835-4312dc9a7ec1.png)

I tried to troubleshoot it myself by looking at these functions:

https://github.com/fs-geofs/UserManager/blob/470aea765b7eb201a1bc68fab21c4bf37c0301fe/routes.go#L156

https://github.com/fs-geofs/UserManager/blob/c06ce65b34b0a5ba154e8ad3723f6c2abf7b2aee/LDAPHandler.go#L158

But I couldn't figure it out.

**Comment by SpeckiJ** [comment]
Should be fixed with commit https://github.com/fs-geofs/UserManager/commit/c8e4bcad6b46864ceee250d0b3137f6579fa86a6

Note: Application needs to be redeployed for changes to take effect.

**Comment by noerw** [comment]
7f7562b is now deployed
